// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5124398390309505016),
      name: 'Habit',
      lastPropertyId: const obx_int.IdUid(10, 8482515222194170117),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3936028245061844139),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5280915492244301778),
            name: 'name',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 870668693399852844),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1935754086031919179),
            name: 'streak',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3087926695973412499),
            name: 'checked',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 239594852941344809),
            name: 'lastChecked',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 6032707207139033931),
            name: 'flamesId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 1880330948544529158),
            relationTarget: 'Flames'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 8482515222194170117),
            name: 'hid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(6, 5882870495616100749))
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'notifications', srcEntity: 'Noti', srcField: 'habit')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 7703370628805739742),
      name: 'UserSettings',
      lastPropertyId: const obx_int.IdUid(3, 8239271670242573714),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5194649802952295894),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1933215418772400176),
            name: 'isDarkMode',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8239271670242573714),
            name: 'localeCode',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(5, 3468389726770743757),
      name: 'Flames',
      lastPropertyId: const obx_int.IdUid(2, 7893018180176263494),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7629435127221689789),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7893018180176263494),
            name: 'flames',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'habits', srcEntity: 'Habit', srcField: 'flames')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 97916875582895082),
      name: 'Noti',
      lastPropertyId: const obx_int.IdUid(7, 4330252826899623908),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1482330492219254954),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5552768428740900863),
            name: 'notificationTime',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1160647007180173718),
            name: 'habitId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(5, 6100367867593498189),
            relationTarget: 'Habit'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 4330252826899623908),
            name: 'nid',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(7, 6100416741096594086))
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(7, 97916875582895082),
      lastIndexId: const obx_int.IdUid(7, 6100416741096594086),
      lastRelationId: const obx_int.IdUid(1, 2635517406211560794),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [
        2792962975620706389,
        5087108227991498369,
        4990814244432181715
      ],
      retiredIndexUids: const [8292585228963820127, 6299715059468388470],
      retiredPropertyUids: const [
        2736417746403495448,
        128407861724487823,
        4175324024939664385,
        629970220138052795,
        6949370414103273680,
        2028968676938064357,
        7247327071934980800,
        5170222834347141701,
        5398120625478593145,
        3409022249451945585,
        3970308011056848547,
        5266556269331392138,
        231626534103152194,
        5996584503638591353,
        719692264286726136
      ],
      retiredRelationUids: const [2635517406211560794],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Habit: obx_int.EntityDefinition<Habit>(
        model: _entities[0],
        toOneRelations: (Habit object) => [object.flames],
        toManyRelations: (Habit object) => {
              obx_int.RelInfo<Noti>.toOneBacklink(
                      6, object.id, (Noti srcObject) => srcObject.habit):
                  object.notifications
            },
        getId: (Habit object) => object.id,
        setId: (Habit object, int id) {
          object.id = id;
        },
        objectToFB: (Habit object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final descriptionOffset = fbb.writeString(object.description);
          final hidOffset = fbb.writeString(object.hid);
          fbb.startTable(11);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, descriptionOffset);
          fbb.addInt64(3, object.streak);
          fbb.addBool(4, object.checked);
          fbb.addInt64(6, object.lastChecked.millisecondsSinceEpoch);
          fbb.addInt64(8, object.flames.targetId);
          fbb.addOffset(9, hidOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final hidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 22, '');
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final lastCheckedParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0));
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final streakParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final checkedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 12, false);
          final object = Habit(
              hidParam, nameParam, descriptionParam, lastCheckedParam,
              id: idParam, streak: streakParam, checked: checkedParam);
          object.flames.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          object.flames.attach(store);
          obx_int.InternalToManyAccess.setRelInfo<Habit>(
              object.notifications,
              store,
              obx_int.RelInfo<Noti>.toOneBacklink(
                  6, object.id, (Noti srcObject) => srcObject.habit));
          return object;
        }),
    UserSettings: obx_int.EntityDefinition<UserSettings>(
        model: _entities[1],
        toOneRelations: (UserSettings object) => [],
        toManyRelations: (UserSettings object) => {},
        getId: (UserSettings object) => object.id,
        setId: (UserSettings object, int id) {
          object.id = id;
        },
        objectToFB: (UserSettings object, fb.Builder fbb) {
          final localeCodeOffset = fbb.writeString(object.localeCode);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addBool(1, object.isDarkMode);
          fbb.addOffset(2, localeCodeOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final localeCodeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final isDarkModeParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 6, false);
          final object = UserSettings(localeCodeParam,
              id: idParam, isDarkMode: isDarkModeParam);

          return object;
        }),
    Flames: obx_int.EntityDefinition<Flames>(
        model: _entities[2],
        toOneRelations: (Flames object) => [],
        toManyRelations: (Flames object) => {
              obx_int.RelInfo<Habit>.toOneBacklink(
                      9, object.id, (Habit srcObject) => srcObject.flames):
                  object.habits
            },
        getId: (Flames object) => object.id,
        setId: (Flames object, int id) {
          object.id = id;
        },
        objectToFB: (Flames object, fb.Builder fbb) {
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.flames);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final flamesParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          final object = Flames(id: idParam, flames: flamesParam);
          obx_int.InternalToManyAccess.setRelInfo<Flames>(
              object.habits,
              store,
              obx_int.RelInfo<Habit>.toOneBacklink(
                  9, object.id, (Habit srcObject) => srcObject.flames));
          return object;
        }),
    Noti: obx_int.EntityDefinition<Noti>(
        model: _entities[3],
        toOneRelations: (Noti object) => [object.habit],
        toManyRelations: (Noti object) => {},
        getId: (Noti object) => object.id,
        setId: (Noti object, int id) {
          object.id = id;
        },
        objectToFB: (Noti object, fb.Builder fbb) {
          final notificationTimeOffset =
              fbb.writeString(object.notificationTime);
          final nidOffset = fbb.writeString(object.nid);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(3, notificationTimeOffset);
          fbb.addInt64(5, object.habit.targetId);
          fbb.addOffset(6, nidOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nidParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 16, '');
          final notificationTimeParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 10, '');
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final object = Noti(nidParam, notificationTimeParam, id: idParam);
          object.habit.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          object.habit.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Habit] entity fields to define ObjectBox queries.
class Habit_ {
  /// See [Habit.id].
  static final id = obx.QueryIntegerProperty<Habit>(_entities[0].properties[0]);

  /// See [Habit.name].
  static final name =
      obx.QueryStringProperty<Habit>(_entities[0].properties[1]);

  /// See [Habit.description].
  static final description =
      obx.QueryStringProperty<Habit>(_entities[0].properties[2]);

  /// See [Habit.streak].
  static final streak =
      obx.QueryIntegerProperty<Habit>(_entities[0].properties[3]);

  /// See [Habit.checked].
  static final checked =
      obx.QueryBooleanProperty<Habit>(_entities[0].properties[4]);

  /// See [Habit.lastChecked].
  static final lastChecked =
      obx.QueryDateProperty<Habit>(_entities[0].properties[5]);

  /// See [Habit.flames].
  static final flames =
      obx.QueryRelationToOne<Habit, Flames>(_entities[0].properties[6]);

  /// See [Habit.hid].
  static final hid = obx.QueryStringProperty<Habit>(_entities[0].properties[7]);

  /// see [Habit.notifications]
  static final notifications =
      obx.QueryBacklinkToMany<Noti, Habit>(Noti_.habit);
}

/// [UserSettings] entity fields to define ObjectBox queries.
class UserSettings_ {
  /// See [UserSettings.id].
  static final id =
      obx.QueryIntegerProperty<UserSettings>(_entities[1].properties[0]);

  /// See [UserSettings.isDarkMode].
  static final isDarkMode =
      obx.QueryBooleanProperty<UserSettings>(_entities[1].properties[1]);

  /// See [UserSettings.localeCode].
  static final localeCode =
      obx.QueryStringProperty<UserSettings>(_entities[1].properties[2]);
}

/// [Flames] entity fields to define ObjectBox queries.
class Flames_ {
  /// See [Flames.id].
  static final id =
      obx.QueryIntegerProperty<Flames>(_entities[2].properties[0]);

  /// See [Flames.flames].
  static final flames =
      obx.QueryIntegerProperty<Flames>(_entities[2].properties[1]);

  /// see [Flames.habits]
  static final habits = obx.QueryBacklinkToMany<Habit, Flames>(Habit_.flames);
}

/// [Noti] entity fields to define ObjectBox queries.
class Noti_ {
  /// See [Noti.id].
  static final id = obx.QueryIntegerProperty<Noti>(_entities[3].properties[0]);

  /// See [Noti.notificationTime].
  static final notificationTime =
      obx.QueryStringProperty<Noti>(_entities[3].properties[1]);

  /// See [Noti.habit].
  static final habit =
      obx.QueryRelationToOne<Noti, Habit>(_entities[3].properties[2]);

  /// See [Noti.nid].
  static final nid = obx.QueryStringProperty<Noti>(_entities[3].properties[3]);
}
