// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'model.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 7703370628805739742),
      name: 'UserSettings',
      lastPropertyId: const obx_int.IdUid(3, 8239271670242573714),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5194649802952295894),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1933215418772400176),
            name: 'isDarkMode',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 8239271670242573714),
            name: 'localeCode',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(7, 97916875582895082),
      lastIndexId: const obx_int.IdUid(7, 6100416741096594086),
      lastRelationId: const obx_int.IdUid(1, 2635517406211560794),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [
        2792962975620706389,
        5087108227991498369,
        4990814244432181715,
        5124398390309505016,
        3468389726770743757,
        97916875582895082
      ],
      retiredIndexUids: const [8292585228963820127, 6299715059468388470],
      retiredPropertyUids: const [
        2736417746403495448,
        128407861724487823,
        4175324024939664385,
        629970220138052795,
        6949370414103273680,
        2028968676938064357,
        7247327071934980800,
        5170222834347141701,
        5398120625478593145,
        3409022249451945585,
        3970308011056848547,
        5266556269331392138,
        231626534103152194,
        5996584503638591353,
        719692264286726136,
        3936028245061844139,
        5280915492244301778,
        870668693399852844,
        1935754086031919179,
        3087926695973412499,
        239594852941344809,
        6032707207139033931,
        8482515222194170117,
        7629435127221689789,
        7893018180176263494,
        1482330492219254954,
        5552768428740900863,
        1160647007180173718,
        4330252826899623908
      ],
      retiredRelationUids: const [2635517406211560794],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    UserSettings: obx_int.EntityDefinition<UserSettings>(
        model: _entities[0],
        toOneRelations: (UserSettings object) => [],
        toManyRelations: (UserSettings object) => {},
        getId: (UserSettings object) => object.id,
        setId: (UserSettings object, int id) {
          object.id = id;
        },
        objectToFB: (UserSettings object, fb.Builder fbb) {
          final localeCodeOffset = fbb.writeString(object.localeCode);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addBool(1, object.isDarkMode);
          fbb.addOffset(2, localeCodeOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final localeCodeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final isDarkModeParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 6, false);
          final object = UserSettings(localeCodeParam,
              id: idParam, isDarkMode: isDarkModeParam);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [UserSettings] entity fields to define ObjectBox queries.
class UserSettings_ {
  /// See [UserSettings.id].
  static final id =
      obx.QueryIntegerProperty<UserSettings>(_entities[0].properties[0]);

  /// See [UserSettings.isDarkMode].
  static final isDarkMode =
      obx.QueryBooleanProperty<UserSettings>(_entities[0].properties[1]);

  /// See [UserSettings.localeCode].
  static final localeCode =
      obx.QueryStringProperty<UserSettings>(_entities[0].properties[2]);
}
